spring:

  application:
    name: app

  jpa:
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update

    output:
      ansi:
        enabled: always

  profiles:
    default: development

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    org:
      springframework:
        test:
          context: DEBUG
        boot:
          test: DEBUG

sentry:
  dsn: https://2bebb6b706e397e7fa57d21b27d71a9e@o4509852853731328.ingest.de.sentry.io/4509852892856400
  send-default-pii: true